project:
  type: website

website:
  title: "Meu Blog"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: about.qmd
        text: Sobre

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
